debug = 0
output = /tmp/stunnel.log
cert = /etc/stunnel/stunnel.pem

[openvpn-tcp]
connect = PORT_TCP
accept = PORT_SSL

[openvpn-udp]
connect = PORT_UDP
accept = 444

[ssh]
connect = 22
accept = 445

[dropbear]
connect = 442
accept = 446